UILD-392: Complex lookups - Refactor the Authority Lookup
FOLIO-EIS/ui-linked-data pull request #327
Opened 2024-09-27 08:59 UTC by SKarolFolio

[https://folio-org.atlassian.net/browse/UILD-392](https://folio-org.atlassian.net/browse/UILD-392)

2024-09-30 23:55 UTC, pkjacob approved these changes

2024-10-01 08:02 UTC, s3fs requested changes
Please check for spelling errors.

2024-10-02 09:41 UTC, SKarolFolio commented on src/common/hooks/useSearchFiltersData.ts
> +    } catch (error) {
added todo comment

2024-10-02 11:17 UTC, s3fs approved these changes

2024-10-02 11:25 UTC, merged